name: Consistently run every 5 minutes no matter what.

# **What it does**: This action runs every 5 minutes.
# **Why we have it**: To learn GitHub actions to automate nightly builds.
# **Who does it impact**: Me :-)

on:
  schedule:
    - cron: 1,6,11,16,21,26,31,36,41,46,51,56 * * * *
    # SEE: https://crontab.guru/#*/5_*_*_*_*
    # Seems like github does not allow step values with a / for example `cron: */5 * * * *`
    # SEE: https://github.com/ekagi/Automated-App-Store-Submits/actions/runs/2565144530/workflow
    # All github actions run at UTC times

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: When am I running
        run: echo "Hi, I just automatically ran at ... $(date +'%Y%m%d_%H%M%S')"
